version: '3'

services:
  web:
    build:
      dockerfile: dev.DockerFile
      context: .
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "8080:8080"
    environment:
      # - CHOKIDAR_USEPOLLING=true
    #  pull request still in process
    # - CHOKIDAR_INTERVAL=1000
    command: npm run dev